### ISSUE TITLE
some requests

### ISSUE THREAD

**Issue by fafaraway** [freebaser/FreebTip#3]
Hi, thanks for update
I have some requests hope you can consider
option to 
toggle player's title/realm/guildrank
hide tooltip while in combat
remove fade time (immediately hide tooltip when cursor move away from player or object)
item/achievement icon like this one https://github.com/Xruptor/XanTooltipIcon
really thanks for your hard work :smile:

**Comment by freebaser** [comment]
[IDCard](http://www.wowinterface.com/downloads/info4507-IDCard.html) works for me already.

The other requests will likely be added in the coming days/weeks ... ;p
